"""Ollama-powered helper methods for intent and analysis."""

from __future__ import annotations

import json
from time import perf_counter
from typing import Iterable, Optional

from langchain_ollama import ChatOllama

from src.logging_config import get_logger


logger = get_logger(__name__)


class OllamaService:
    """Ollama-powered LLM service for intent detection and response generation.

    Wraps :class:`langchain_ollama.ChatOllama` to provide task-specific
    methods used throughout the Jira MCP client.  All calls are made with
    ``temperature=0`` for deterministic, reproducible outputs.

    Args:
        model: Ollama model identifier to use for all inference calls
            (e.g. ``"llama3.2:latest"``).  The model must be available
            locally via the Ollama daemon.
    """

    def __init__(self, model: str) -> None:
        """Initialise the service with the specified Ollama model.

        Args:
            model: Ollama model tag (e.g. ``"llama3.2:latest"``).  The model
                must be pulled and available via the local Ollama daemon.
        """
        self._llm = ChatOllama(model=model, temperature=0)
        logger.info("Configured Ollama service", extra={"model": model})

    def detect_intent(self, user_input: str) -> str:
        """Classify a user query into a Jira workflow intent.

        Sends a zero-shot classification prompt to the LLM and parses the
        JSON response.  The model is instructed to return one of three labels:
        ``"issue_details"``, ``"sprint_insights"``, or ``"clarify"``.

        Any unrecognised label or JSON parse failure falls back to
        ``"clarify"``.

        Args:
            user_input: Raw natural-language query from the user.

        Returns:
            One of ``"issue_details"``, ``"sprint_insights"``, or
            ``"clarify"``.
        """
        started_at = perf_counter()
        prompt = (
            "Classify this Jira request into one label: "
            "issue_details, sprint_insights, team_status, or clarify. "
            "Use 'team_status' for requests about team member statuses, standup reports, "
            "or per-assignee issue summaries. "
            "Return JSON only with schema {\\\"intent\\\": \\\"<label>\\\"}.\n"
            f"Request: {user_input}"
        )
        raw = self._llm.invoke(prompt).content
        intent = self._safe_json_extract(raw).get("intent", "clarify")
        resolved_intent = (
            intent
            if intent in {"issue_details", "sprint_insights", "team_status", "clarify"}
            else "clarify"
        )
        logger.info(
            "Detected workflow intent",
            extra={
                "intent": resolved_intent,
                "duration_ms": round((perf_counter() - started_at) * 1000, 2),
                "input_length": len(user_input),
            },
        )
        return resolved_intent

    def infer_board_name(self, user_input: str) -> Optional[str]:
        """Ask the LLM to extract a Scrum board name from *user_input*.

        Used as a fallback when regex-based extraction in
        :func:`~src.graph.parsing.extract_board_name` yields no result.
        Sends a structured extraction prompt and parses the ``"board_name"``
        field from the JSON response.

        Args:
            user_input: Raw natural-language query that may reference a
                Scrum board.

        Returns:
            The extracted board name string, or ``None`` if the LLM returns
            an empty or unresolvable value.
        """
        started_at = perf_counter()
        prompt = (
            "Extract scrum board name from this Jira request. "
            "Return JSON only with schema {\\\"board_name\\\": \\\"<name or empty>\\\"}.\n"
            f"Request: {user_input}"
        )
        raw = self._llm.invoke(prompt).content
        board_name = self._safe_json_extract(raw).get("board_name", "").strip()
        resolved = board_name or None
        logger.info(
            "Inferred board name",
            extra={
                "board_name_detected": bool(resolved),
                "duration_ms": round((perf_counter() - started_at) * 1000, 2),
            },
        )
        return resolved

    def summarize_issues(self, issues_text: str) -> str:
        """Generate a scrum master–focused sprint analysis narrative.

        Sends the raw issues text to the LLM with a prompt instructing it to
        highlight delivery risk, blockers, and recommended next actions.

        Args:
            issues_text: Plain-text or JSON representation of the active
                sprint issues.

        Returns:
            A concise analytical narrative suitable for a scrum master review,
            as generated by the LLM.
        """
        started_at = perf_counter()
        prompt = (
            "Analyze the active sprint Jira issues and provide concise observations for a scrum master. "
            "Focus on delivery risk, blockers, and next actions.\n\n"
            f"Issues:\n{issues_text}"
        )
        summary = str(self._llm.invoke(prompt).content)
        logger.info(
            "Generated sprint analysis",
            extra={
                "duration_ms": round((perf_counter() - started_at) * 1000, 2),
                "issues_length": len(issues_text),
                "summary_length": len(summary),
            },
        )
        return summary

    def generate(self, prompt: str) -> str:
        """Send a fully-formed prompt to the LLM and return its text response."""
        started_at = perf_counter()
        response = str(self._llm.invoke(prompt).content)
        logger.info(
            "Generated LLM response",
            extra={
                "duration_ms": round((perf_counter() - started_at) * 1000, 2),
                "prompt_length": len(prompt),
                "response_length": len(response),
            },
        )
        return response

    def stream_generate(self, prompt: str) -> Iterable[str]:
        """Send a fully-formed prompt to the LLM and stream response chunks."""
        started_at = perf_counter()
        chunk_count = 0
        try:
            for chunk in self._llm.stream(prompt):
                content = getattr(chunk, "content", "")
                if content:
                    chunk_count += 1
                    yield str(content)
        except Exception:
            logger.exception("LLM streaming failed")
            raise
        finally:
            logger.info(
                "Completed LLM response stream",
                extra={
                    "duration_ms": round((perf_counter() - started_at) * 1000, 2),
                    "prompt_length": len(prompt),
                    "chunk_count": chunk_count,
                },
            )

    def stream_markdown(self, text: str) -> Iterable[str]:
        """Improve and stream *text* as formatted Markdown via the LLM.

        Sends *text* to the LLM with a readability-improvement prompt that
        preserves meaning and Markdown structure without inventing new facts.
        Yields response chunks incrementally.

        Args:
            text: Raw Jira content to be reformatted for readability.

        Yields:
            Non-empty Markdown content string chunks as they arrive from the
            model.

        Raises:
            Exception: Any exception raised by the underlying LLM stream is
                propagated after logging.
        """
        logger.info("Streaming markdown response", extra={"input_length": len(text)})
        prompt = (
            "You are a Jira assistant. Improve readability while preserving meaning and markdown structure. "
            "Do not invent facts.\n\n"
            f"Input:\n{text}"
        )
        chunk_count = 0
        try:
            for chunk in self._llm.stream(prompt):
                content = getattr(chunk, "content", "")
                if content:
                    chunk_count += 1
                    yield str(content)
        except Exception:
            logger.exception("Markdown streaming failed")
            raise
        finally:
            logger.info("Completed markdown stream", extra={"chunk_count": chunk_count})

    def build_team_status_prompt(self, team_status_payload: dict) -> str:
        """Build a prompt asking the LLM to generate a per-member status report for the scrum master."""
        board_name = team_status_payload.get("board_name", "the board")
        members = team_status_payload.get("team_members", [])
        return (
            f"You are a Jira assistant preparing a standup/status report for the scrum master "
            f"of the '{board_name}' board.\n"
            "For each team member listed below, summarize their current issue statuses "
            "(open, in-progress, completed, blocked) and highlight any blockers or risks.\n"
            "After the individual summaries, provide an overall team status section with "
            "actionable insights and recommended next steps for the scrum master.\n\n"
            f"Team status data:\n{json.dumps({'board_name': board_name, 'team_members': members}, indent=2)}"
        )

    def _safe_json_extract(self, raw: object) -> dict:
        """Parse a JSON dict from a raw LLM response, tolerating extra text.

        First attempts a strict :func:`json.loads` parse of the full response.
        If that fails, falls back to locating the outermost ``{...}`` block
        and parsing that substring.  Both failure paths are logged at
        ``WARNING`` level and return an empty dict rather than raising.

        Args:
            raw: Raw LLM response object; converted to ``str`` before
                parsing.

        Returns:
            Parsed dictionary, or an empty dict if no valid JSON object can
            be extracted.
        """
        text = str(raw).strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Basic fallback for models that wrap JSON with text
            start = text.find("{")
            end = text.rfind("}")
            if start != -1 and end != -1 and end > start:
                try:
                    return json.loads(text[start : end + 1])
                except json.JSONDecodeError:
                    logger.warning("Failed to decode wrapped JSON response")
                    return {}
            logger.warning("Failed to decode JSON response")
            return {}
